### ISSUE TITLE
Support for SSL in Sitemaps

### ISSUE THREAD

**Issue by marbetschar** [meldsolutions/Meld-Google-Sitemaps#21]
We are currently running a fully SSL protected website and have installed the Google Sitemaps plugin. Unfortunately the protocol on sitemap generation is hardcoded.

Also I've seen you are not using $.createHREF(...complete=true) for the url creation.
Is there any specific reason why?

Basically my idea was, you may just want to use $.createHREF for sitemap URL generation?

Unfortunately the $.createHREF does not support SSL by now too. Therefore I've also opened an issue in the mura repo for this case:
https://github.com/blueriver/MuraCMS/issues/1298

But maybe there is any other workaround I'm missing right now?

**Comment by grantshepert** [comment]
6.2 now supports full SSL, will investigate

**Comment by andrew-dixon** [comment]
@grantshepert - I've added a pull request for this.
