### ISSUE TITLE
Not picking up values for priority, exclude and frequency

### ISSUE THREAD

**Issue by jochemd** [meldsolutions/Meld-Google-Sitemaps#24]
We have an instance where the plugin does not appear to pick up the values for priority, exclude and frequency for most of our pages. Mura version 6.1.5870, plugin version 3.0.0.

The problem appears to be related to our extensive use of custom types. The plugin is explicitly looking for subType = 'Default' (line 88 of MeldGoogleSitemapsManager.cfc) for when it looks up the extended attributes, which means that query returns 0 rows. If I remove that condition, the query returns rows and the correct sitemap gets generated. It looks like removing that condition is save since the QofQ in getValues() filters on contentHistID anyway.

**Comment by grantshepert** [comment]
The issue with this is that it could pick up class extensions of the same name from different subtypes, and chaos would ensue (wrong values or the dreaded value,value concatenation).
