### ISSUE TITLE
Saving settings doesn't work

### ISSUE THREAD

**Issue by am2605** [meldsolutions/Meld-Google-Sitemaps#29]
Hello,

I've just installed this plugin on our Mura instance (version 6.0.5367).  It seems to install correctly, however when I go to the Settings -> Edit settings and make any changes, then press update, the settings retain their default values and my changes don't appear to have been saved.

For example if I go to Settings -> Edit settings, then check "Sitemap Enabled", and then click "Update", when it comes back to the settings page, the settings appear as:

    Sitemap Enabled: No
    Frequency: Weekly,
    Email: suppressed

Any ideas?

**Comment by Tigerlady** [comment]
I use this quite a lot on various sites.   would it be possible to see your settings.  i can offer to do an onlline session if you like.  Although i am not the developer but i use it on more than 10 sites so have worked through several issues.

**Comment by grantshepert** [comment]
I've just checked and confirmed this is working as expected.

Can you check and confirm you have a Class Extension called Custom/MeldGoogleSitemaps? This is where the settings are stored. If not, uninstall/reinstalled the plugin.

**Comment by am2605** [comment]
Thanks for getting back to me on this @grantshepert and @Tigerlady.

I can confirm the MeldGoogleSitemaps Class Extension is present, and I have also tried uninstalling and reinstalling.

I turned on debug on my server (which is Adobe CF11), and put a bit of debug in admin/controller/settings.cfc and it looks to me that in every call to doGetSettings() the sitemapsObject has the default values:

eg. if I add this at line 103:

<cfset foo = SerializeJSON(siteMapsObject.getAllValues())>
<cftrace var="foo"> (line 

The output, even after pressing save, is always:

```javascript
{"SUBTYPE":"MeldGoogleSitemaps","Location":"site","ERRORS":{},"EXTENDAUTOCOMPLETE":true,"ModuleID":"7BF4F705-A160-A8D9-71A00AA271C22C39","SOURCEITERATOR":"","EXTENDSETID":"724A3AE0-A92A-8E9F-E6C0B369D30935A6","SITEID":"ahic","Email":"","DateLastCreate":"","REMOTEID":"","EXTENDDATATABLE":"tclassextenddata","FROMMURACACHE":false,"Frequency":"weekly","Enabled":0,"TimeOfDay":"","ID":"ahic","TYPE":"Custom","EXTENDDATA":""}
```

Not sure what else to try?

**Comment by am2605** [comment]
FYI - Tried this on a fairly clean 6.2 install, also on ACF11, but against MySQL (versus Oracle on my work server).  It worked fine.

So it's got me beat.  I'll persist with it for a little while and let you know how I get on, but I expect this is environmental rather than a bug so I wouldn't expect you guys to spend any more time investigating.

Unless it's an Oracle thing...but I doubt it.

**Comment by grantshepert** [comment]
Ah, yes, that absolutely is it. The plugin doesn't support Oracle.

**Comment by am2605** [comment]
Thanks Grant.  Sorry, I didn't think to specify that in my initial report.

Are you able to give any info on where the issue is with using Oracle?  Is it something I might be able to make a fix for?
