### ISSUE TITLE
Any Version work with Mura 5.2 and ColdFusion 10?

### ISSUE THREAD

**Issue by TAllenSr** [meldsolutions/Meld-Google-Sitemaps#31]
Hello! I have a customer with Mura 5.2.2374 and can not upgrade, running on ColdFusion 10. Is there a version of your plug-in that will work with that combo? I have tried the latest and the "old 5.1" version, and I get a "DATA is not defined" when it tries to create the default Bean using Bean Factory.

**Comment by meldsolutions** [comment]
Sorry, no.
