### ISSUE TITLE
can't convert value useMuraDefault to a datetime value

### ISSUE THREAD

**Issue by Tigerlady** [meldsolutions/Meld-Google-Sitemaps#40]
Hello,  I just installed on a new site launch and am having an issue when I click on the settings tab.  I get the following error.

can't convert value useMuraDefault to a datetime value

I am running on Lucee 4.5  and Mura 7.0.6860
Any help would be appreciated.  Thanks. 

can't convert value useMuraDefault to a datetime value at lucee.runtime.functions.displayFormatting.TimeFormat._call(TimeFormat.java:68):68 at lucee.runtime.functions.displayFormatting.TimeFormat.call(TimeFormat.java:56):56 at admin.views.settings.default_cfm$cf.call(/MeldGoogleSitemaps/admin/views/settings/default.cfm:36):36 at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:954):954 at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:858):858 at framework_cfc$cf.udfCall7(/MeldGoogleSitemaps/framework.cfc:1476):1476 at framework_cfc$cf.udfCall(/MeldGoogleSitemaps/framework.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:766):766 at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743 at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1596):1596 at framework_cfc$cf.udfCall2(/MeldGoogleSitemaps/framework.cfc:514):514 at framework_cfc$cf.udfCall(/MeldGoogleSitemaps/framework.cfc):-1 at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111 at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328 at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642 at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524 at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761 at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:414):414 at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:223):223 at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:37):37 at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2268):2268 at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2231):2231 at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456 at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47 at javax.servlet.http.HttpServlet.service(HttpServlet.java:729):729 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291):291 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239):239 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217):217 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106):106 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502):502 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142):142 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79):79 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88):88 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518):518 at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844):844 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673):673 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500):1500 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456):1456 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61 at java.lang.Thread.run(Thread.java:745):745

34: &lt;/li&gt;<br> 35: &lt;li&gt;<br> <b>36: &lt;strong&gt;#rc.mmRBF.key('frequency')#:&lt;/strong&gt; #rc.sData.frequency#, #timeFormat(local.timeofday,&quot;hh:mm TT&quot;)#</b><br> 37: &lt;/li&gt;<br> 38: &lt;li&gt;<br>

**Comment by Tropicalista** [comment]
Please check here: https://github.com/meldsolutions/Meld-Google-Sitemaps/issues/42
