### ISSUE TITLE
can't convert value useMuraDefault to a datetime value

### ISSUE THREAD

**Issue by alfredo23756** [meldsolutions/Meld-Google-Sitemaps#42]
Hello, I just installed on a new site launch and am having an issue when I click on the settings tab. I get the following error.

can't convert value useMuraDefault to a datetime value

I am running on coldfusion 10 and Mura 7.0.6919.
Any help would be appreciated. Thanks.

**Comment by Tropicalista** [comment]
you need to go to settings->edit http://127.0.0.1:50980/plugins/MeldGoogleSitemaps/index.cfm?action=admin:settings.edit and check sitemap enabled
